### ISSUE TITLE
Vercel deployment failed with an error:

### ISSUE THREAD

**Issue by CUZAMARK** [JulzOhern/Gogoanime-and-Hianime-proxy#1]
Here's the error that I am getting while deploying api through vercel:
![Screenshot_2024_1119_164015](https://github.com/user-attachments/assets/1a67e9c4-8289-4a4b-9048-cfcd15e67e86)

**Comment by JulzOhern** [comment]
Use . in vercel output directory

**Comment by JulzOhern** [comment]
> Here's the error that I am getting while deploying api through vercel: ![Screenshot_2024_1119_164015](https://private-user-images.githubusercontent.com/110730813/387628023-1a67e9c4-8289-4a4b-9048-cfcd15e67e86.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI0NDA5MDAsIm5iZiI6MTczMjQ0MDYwMCwicGF0aCI6Ii8xMTA3MzA4MTMvMzg3NjI4MDIzLTFhNjdlOWM0LTgyODktNGE0Yi05MDQ4LWNmY2QxNWU2N2U4Ni5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyNFQwOTMwMDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01YmI3MzAyZjNiMzEwNjE2NDUwNzA1NzhkMmIzZmQxMTM4MWYyOTFjYzJhZTU0ZWUxYjU3MThhMTI2MTBjMmRkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.yF-EzLSk53fJ3b9Nr55FBBphs_tnTiX1E9nxBtCI4bc)
