### ISSUE TITLE
Help!!

### ISSUE THREAD

**Issue by devachandru** [JulzOhern/Gogoanime-and-Hianime-proxy#3]
Hey I deployed this repo successfully in vercel but it seems like it's not working, but your url is working fine : https://gogoanime-and-hianime-proxy.vercel.app. Mine is not bypassing the CORS errors : https://bypass-cors-ten.vercel.app

Can you help ?

**Comment by anime-kun32** [comment]
Same here

**Comment by anime-kun32** [comment]
Just figured out how to fix this.  in your .env set the base URL to your vercel deployment without / at the end. that solves everything

**Comment by devachandru** [comment]
It works. Thank you

**Comment by anime-kun32** [comment]
You're welcome
